version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_chat_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat_app
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init_db:/docker-entrypoint-initdb.d
    networks:
      - chat_network

networks:
  chat_network:
    driver: bridge
