version: '3.9'

services:
  backend:
    build: .
    container_name: backend_chat
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: ""
      DB_NAME: chat_app
    networks:
      - chat_network

networks:
  chat_network:
    driver: bridge